#!/usr/bin/env bash

# Current Theme
theme="$HOME/.config/rofi/applets/type-2/style-2"

# Options
editor='󰨞'
manager=''
terminal=''

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "Dotfiles" \
		-theme ${theme}.rasi
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$editor\n$terminal\n$manager" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$editor) #? open dotfiles in editor code
	code $DOTFILES_PATH
	;;
$manager) #? open dotfiles in file manager
	thunar $DOTFILES_PATH
	;;
$terminal) #? open dotfiles in terminal
	kitty --directory $DOTFILES_PATH
	;;
esac
