#!/bin/bash

file="$DOTFILES_PATH/doc/shortcuts.yaml"

rofi_cmd() {
	rofi -dmenu -mesg "Selecciona un puerto" # -theme $HOME/.config/rofi/launchers/type-2/style-7.rasi
}

readarray -t ports < <(yq -r '.rofi.ports | to_entries[] | " \(.key) : \(.value)"' $file)
selected=$(printf '%s\n' "${ports[@]}" | rofi_cmd)

if [ -n "$selected" ]; then
	puerto=$(echo "$selected" | awk '{print $1}')
	xdg-open "http://localhost:$puerto" &
fi
