#!/usr/bin/env bash

file="$DOTFILES_PATH/doc/shortcuts.yaml"

rofi_cmd() {
	rofi -dmenu -mesg "$1" #-theme $HOME/.config/rofi/launchers/type-2/style-2.rasi
}

# ? change between screenlayout files
screenlayout() {
	file="$HOME/.screenlayout/"
	screen=$(ls "$file")
	selected=$(printf '%s\n' "${screen[@]}" | rofi_cmd "Selecciona Tipo de pantalla")
	if [ -n "$selected" ]; then
		sh "$file/$selected"
		pkill conky && (conky -c ~/.conkyrc) &
		if [ ! -z "$(pgrep qtile)" ]; then
			qtile_manager -r
		fi
	fi
}

# ? open dotfiles folder
dotfiles() {
	theme="$HOME/.config/rofi/applets/type-2/style-2"
	# Options
	editor='󰨞'
	manager=''
	terminal=''
	rofi_cmd() {
		rofi -dmenu -p "Dotfiles" -theme "${theme}".rasi
	}
	chosen=$(echo -e "$editor\n$terminal\n$manager" | rofi_cmd)
	case ${chosen} in
	"$editor") code "$DOTFILES_PATH" ;;
	"$manager") thunar $DOTFILES_PATH ;;
	"$terminal") kitty --directory "$DOTFILES_PATH" ;;
	esac
}

# ? select window and show information. Copy to clipboard selected info
window_properties() {
	WINDOW_ID=$(xdotool selectwindow)
	WINDOW_NAME=$(xprop -id "$WINDOW_ID" WM_NAME | cut -d '"' -f 2)
	WINDOW_ROLE=$(xprop -id "$WINDOW_ID" WM_WINDOW_ROLE | cut -d '"' -f 2)
	WM_CLASS=$(xprop -id "$WINDOW_ID" WM_CLASS | cut -d '"' -f 2)

	OUTPUT="CLASS » $WM_CLASS\nROLE  » $WINDOW_ROLE\nNAME  » $WINDOW_NAME"
	SELECTION=$(echo -e "$OUTPUT" | rofi_cmd "Informacion de ventana")
	if [ -n "$SELECTION" ]; then
		TO_COPY=$(echo "$SELECTION" | cut -d '»' -f 2- | sed 's/^ *//')
		echo "$TO_COPY" | xclip -selection clipboard
	fi
}

# ? open web browser with selected url
localhost() {
	readarray -t ports < <(yq -r '.rofi.ports | to_entries[] | " \(.key) : \(.value)"' $file)
	selected=$(printf '%s\n' "${ports[@]}" | rofi_cmd "Selecciona un puerto")
	if [ -n "$selected" ]; then
		port=$(echo "$selected" | awk '{print $1}')
		xdg-open "http://localhost:$port" &
	fi
}

# ? run shell scripts
scripts() {
	readarray -t scripts < <(yq -r '.rofi.apps | to_entries[] | "\(.value)"' $file)
	selected=$(printf '%s\n' "${scripts[@]}" | rofi_cmd "Ejecuta script")
	if [ -n "$selected" ]; then
		s=$(echo "$selected" | awk '{print $NF}')
		sh "$HOME/$s" &
	fi
}

case $1 in
--apps) scripts ;;
--dotf) dotfiles ;;
--localhost) localhost ;;
--screen) screenlayout ;;
--windows) window_properties ;;
esac
