[general]
live_config_reload = true
import             = ["~/.config/alacritty/current-theme.toml"]

# [terminal.shell]
# program = "/bin/zellij"

[cursor]
blink_interval   = 750
blink_timeout    = 5
thickness        = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape    = "Beam"

[font]
builtin_box_drawing = true
size                = 12

[font.normal]
family = "GeistMono Nerd Font Mono"
style  = "Bold"

[font.bold]
style  = "Bold"

[font.bold_italic]
style  = "Bold Italic"

[font.italic]
style  = "Italic"

[scrolling]
history    = 2000
multiplier = 3

[selection]
save_to_clipboard     = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations               = "full"
decorations_theme_variant = "None"
dynamic_padding           = true
dynamic_title             = true
resize_increments         = false

[window.class]
general  = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 8
y = 8

[keyboard]
bindings = [
	{key = "F11", action = "ToggleFullscreen"},
]
