#!/usr/bin/env bash
# Generated on 2024-10-25 17:16

Print
	flameshot gui
XF86AudioLowerVolume
	amixer set Master 5%-
XF86AudioRaiseVolume
	amixer set Master 5%+
XF86AudioMute
	amixer -D pulse set Master toggle
XF86AudioNext
	playerctl next
XF86AudioPlay
	playerctl play-pause
XF86AudioPrev
	playerctl previous
XF86AudioStop
	playerctl stop
super + F1
	brave
super + F2
	code
super + F6
	ferdium
super + F7
	virtualbox
super + F8
	thunar
super + F9
	thunderbird
super + F10
	spotube
super + F11
	kodi
super + a
	rofi -show combi
super + b
	blueman-manager
super + c
	chromium
super + e
	code
super + f
	firefox
super + g
	sourcegit
super + k
	keepassxc
super + m
	pragha
super + r
	retroarch
super + s
	pamac-manager
super + v
	vlc --video-on-top
super + x
	~/.config/rofi/scripts/powermenu
super + less
	qalculate-gtk
super + Return
	kitty
super + ctrl + p
	sh ~/.config/picom/picom-toogle.sh
super + ctrl + x
	pkill -USR1 -x sxhkd
super + ctrl + Print
	xfce4-screenshooter
super + ctrl + Escape
	xfce4-taskmanager
super + ctrl + F1
	brave --tor
alt + Escape
	xkill
alt + Print
	scrot 'screenshot_%Y%m%d_%H%M%S.jpg' -e 'mv $f $$(xdg-user-dir SCREENSHOTS)'
alt + Left
	variety -p
alt + Right
	variety -n
alt + F1
	~/.config/rofi/scripts/rofi-scripts --dotf
alt + F2
	~/.config/rofi/scripts/rofi-scripts --ports
alt + F3
	~/.config/rofi/scripts/rofi-scripts --screen
alt + F4
	~/.config/rofi/scripts/rofi-scripts --preconfiguration
alt + F5
	~/.config/rofi/scripts/rofi-scripts --windows
alt + F6
	~/.config/rofi/scripts/rofi-scripts --apps
alt + F7
	~/.config/rofi/scripts/shortcuts
alt + ccedilla
	xfce4-clipman-history