#!/usr/bin/env bash
#Generated on 2024-01-20 10:59

Print
	xfce4-screenshooter
XF86AudioLowerVolume
	amixer set Master 5%-
XF86AudioRaiseVolume
	amixer set Master 5%+
XF86AudioMute
	amixer -D pulse set Master 1+ toggle
XF86AudioNext
	playerctl next
XF86AudioPlay
	playerctl play-pause
XF86AudioPrev
	playerctl previous
XF86AudioStop
	playerctl stop
XF86MonBrightnessDown
	xbacklight -dec 5
XF86MonBrightnessUp
	xbacklight -inc 5
alt + Escape
	xfce4-taskmanager
alt + Print
	scrot 'screenshot_%Y%m%d_%H%M%S.jpg' -e 'mv $f $$(xdg-user-dir SCREENSHOTS)'
alt + Left
	variety -p
alt + Right
	variety -n
alt + F1
	rofi -show file-browser-extended
alt + F2
	rofi -show drun
alt + F3
	rofi -show window
alt + F4
	rofi -show ssh
alt + F5
	rofi -show emoji
alt + shift + Return
	thunar
alt + shift + v
	xfce4-clipman-history
alt + shift + h
	rofi -show file-browser-extended -file-browser-dir ~/.config/
alt + shift + j
	rofi -show file-browser-extended -file-browser-dir '~/Proyectos/Git y Workspaces'
alt + shift + l
	rofi -show file-browser-extended -file-browser-dir ~/Proyectos/
super + F1
	brave
super + F2
	code
super + F3
	gimp
super + F4
	rofi-bluetooth
super + F5
	archlinux-tweak-tool
super + F6
	ferdium
super + F7
	virtualbox
super + F8
	thunar
super + F9
	thunderbird
super + F10
	spotube
super + F11
	kodi
super + KP_Enter
	gnome-calculator
super + Return
	kitty
super + a
	xfce4-appfinder
super + b
	bitwarden-desktop
super + c
	chromium
super + e
	code
super + f
	firefox
super + g
	github-desktop
super + m
	pragha
super + r
	retroarch
super + s
	pamac-manager
super + v
	vlc --video-on-top
super + d
	~/.config/rofi/scripts/dotf
super + x
	~/.config/rofi/scripts/powermenu
super + z
	~/.config/rofi/scripts/bookmarks
super + ctrl
	None
super + shift + Escape
	xkill
super + shift + o
	sh ~/.config/picom/picom-toogle.sh
super + shift + s
	pkill -USR1 -x sxhkd
