#!/usr/bin/env sh
##? usage : extra_repos [none]
##? help  : Clone my repos with specific configuration.

# Clone Qtile configuration
git clone https://github.com/AlbertoVf/qtile.git --depth 1 ~/.config/qtile
# Clone terminal scripts
git clone https://github.com/AlbertoVf/shell-scripts --depth 1 ~/.bin
# Clone wallpapers
git clone https://github.com/AlbertoVf/wallpapers.git --depth 1 ~/.wallpapers
# Clone arco-install to install packages
git clone https://github.com/AlbertoVf/arco-install --depth 1
# Clone rofi configuration installer
git clone --depth=1 https://github.com/adi1090x/rofi.git --depth 1 && sh rofi/setup.sh
