#!/usr/bin/env bash
##? usage : my_repos [none]
##? help  : Clone my repos with specific configuration.

git clone https://github.com/AlbertoVf/qtile.git --depth 1 ~/.config/qtile
git clone https://github.com/AlbertoVf/shell-scripts --depth 1 ~/.bin
git clone https://github.com/AlbertoVf/wallpapers.git --depth 1 ~/.wallpapers
