#!/bin/bash

file="$DOTFILES_PATH/doc/shortcuts.yaml"

rofi_cmd() {
	rofi -dmenu -p "Selecciona una aplicacion" #-theme $HOME/.config/rofi/launchers/type-2/style-2.rasi
}

readarray -t apps < <(yq -r '.rofi.apps | to_entries[] | " \(.key) : \(.value)"' $file)
selected=$(printf '%s\n' "${apps[@]}" | rofi_cmd)

if [ -n "$selected" ]; then
	app=$(echo "$selected" | awk '{print $NF}')
	$app
fi
