#!/bin/bash

file="$DOTFILES_PATH/doc/shortcuts.yaml"

rofi_cmd(){
	rofi -dmenu -p "Selecciona una web" #-theme $HOME/.config/rofi/launchers/type-2/style-2.rasi
}

readarray -t bookmarks < <(yq -r '.rofi.bookmarks | to_entries[] | " \(.key) : \(.value)"' $file)
selected=$(printf '%s\n' "${bookmarks[@]}" | rofi_cmd)

if [ -n "$selected" ]; then
	web=$(echo "$selected" | awk '{print $NF}')
	xdg-open $web &
fi
