#!/bin/bash

rofi_bookmarks() {
	# Archivo HTML que deseas leer
	html_file="$DOTFILES_PATH/doc/bookmarks.html"

	# Utiliza grep para extraer los textos de los enlaces del archivo HTML
	links_text=$(grep -o '<[aA] [^>]*>[^<]*</[aA]>' "$html_file" | sed -n 's/.*<[aA] [^>]*>\([^<]*\)<\/[aA]>/\1/p')

	# Convierte los textos de los enlaces en un formato adecuado para rofi
	rofi_input=$(echo -e "$links_text")

	# Utiliza rofi para mostrar los textos de los enlaces y seleccionar uno
	selected_text=$(echo -e "$rofi_input" | rofi -dmenu -p "Selecciona un enlace:")

	# Encuentra la URL correspondiente al enlace seleccionado
	selected_link=$(grep -o '<[aA] [^>]*>[^<]*</[aA]>' "$html_file" | sed -n "/$selected_text/ s/.*href=\"\([^\"]*\)\".*/\1/p")

	# Abre el enlace seleccionado en Firefox
	if [ -n "$selected_link" ]; then
		$BROWSER "$selected_link" &
	fi
}

rofi_bookmarks
