#!/usr/bin/env bash

## Author : Aditya Shakya (adi1090x)
## Github : @adi1090x
#
## Rofi   : Power Menu
#
## Available Styles
#
## style-1   style-2   style-3   style-4   style-5
## style-6   style-7   style-8   style-9   style-10

# Current Theme
dir="$HOME/.config/rofi/powermenu/type-6"
theme='style-6'

# CMDs
uptime="`uptime -p | sed -e 's/up //g'`"
# host=`hostname`

# Options
shutdown=''
reboot=''
lock=''
suspend='󰿅'
logout='󰗼'
date="$(date +"%a %d %b %H:%M")"

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "[$USER] $date" \
		-theme ${dir}/${theme}.rasi
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$shutdown\n$reboot\n$lock\n$logout" | rofi_cmd
}

# Execute Command
run_cmd() {
		if [[ $1 == '--shutdown' ]]; then
			systemctl poweroff
		elif [[ $1 == '--reboot' ]]; then
			systemctl reboot
		elif [[ $1 == '--suspend' ]]; then
			mpc -q pause
			amixer set Master mute
			systemctl suspend
		elif [[ $1 == '--logout' ]]; then
			if [[ "$DESKTOP_SESSION" == 'openbox' ]]; then
				openbox --exit
			elif [[ "$DESKTOP_SESSION" == 'bspwm' ]]; then
				bspc quit
			elif [[ "$DESKTOP_SESSION" == 'i3' ]]; then
				i3-msg exit
			elif [[ "$DESKTOP_SESSION" == 'plasma' ]]; then
				qdbus org.kde.ksmserver /KSMServer logout 0 0 0
			elif [[ "$DESKTOP_SESSION" == 'qtile' ]]; then
				qtile cmd-obj -o cmd -f shutdown
			fi
		fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
	$shutdown)
		run_cmd --shutdown
		;;
	$reboot)
		run_cmd --reboot
		;;
	$lock)
		if [[ -x '/usr/bin/betterlockscreen' ]]; then
			betterlockscreen -l
		elif [[ -x '/usr/bin/i3lock' ]]; then
			i3lock
		fi
		;;
	$suspend)
		run_cmd --suspend
		;;
	$logout)
		run_cmd --logout
		;;
esac
