#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  colorscheme = "palenight"
  colorscheme_bg = "dark"
  enable_guicolors = true
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  automatic_update = true
  default_indent = 2
  enable_statusline_mode = true
  statusline_left_sections = [ 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info', 'search status' ]
  statusline_right_sections = [ 'cursorpos', 'time' ]
  filemanager = 'nerdtree'
  enable_vimfiler_gitstatus = true
  filetree_direction = 'left'

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"
  autocomplete_metod = "coc"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30
[[layers]]
  name = "sudo"
[[layers]]
  name = "colorscheme"
[[layers]]
  name = "core#statusline"
[[layers]]
  name ="core#tabline"

[[layers]]
  name = "format"
  format_on_save = true
[[layers]]
  name = "test"
[[layers]]
  name = "denite"
[[layers]]
  name = 'git'
[[layers]]
  name= 'VersionControl'

[[layers]]
  name = "lang#batch"
[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang"
  clang_flag = ['-I/usr/include']
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"
[[layers]]
  name = "lang#csharp"
  highlight_types = 0
[[layers]]
  name = "lang#dockerfile"
[[layers]]
  name = "lang#go"
[[layers]]
  name = "lang#html"
  emmet_leader_key = "<C-e>"
  emmet_filetyps = ['html']
[[layers]]
  name = 'lang#java'
  java_file_head = [
    '/**',
    ' * @author : `fnamemodify(expand("~"), ":t")`',
    ' * @created : `strftime("%Y-%m-%d")`',
    '**/',
    ''
  ]
[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true
[[layers]]
  name = "lang#kotlin"
[[layers]]
  name = "lang#latex"
[[layers]]
  name = "lang#markdown"
[[layers]]
  name = "lang#php"
[[layers]]
  name = "lang#powershell"
[[layers]]
  name = "lang#python"
  enable_typeinfo = true
[[layers]]
  name = "lang#sh"
[[layers]]
  name = "lang#toml"
[[layers]]
  name = "lang#typescript"
[[layers]]
  name = "lang#vim"
[[layers]]
  name = "lang#xml"