#!/usr/bin/env sh
## ? Help : Get your IP address from the command line.
## ? Usage:
## ?    my_ip

privada="$(ip addr show | grep 'inet.*brd' | awk '{print $2}' | cut -f1 -d'/' | head -n1)"
publica="$(curl -s ifconfig.me | awk '{print $1}')"
echo "{\"publica\":\"$publica\",\"privada\":\"$privada\"}" | jq '.'
curl -s http://ip-api.com/json/$publica | jq '.'
