#!/usr/bin/env sh
## ? Help : Open/Exec a file in the default editor.
## ? Usage:
## ?    run <file>

file=$1
extension="$(echo $file | cut -d '.' -f2-)"
case $file in
*.sh | *.zsh | *.bash) $extension $file ;;
*.py) python $file ;;
*.java) javac $file ;;
*.c | *.h) gcc $file ;;
*.cpp | *.hpp) g++ $file ;;
*.js | *.ts) deno run $file ;;
*.html | *.htm | *.xhtm) xdg-open $file ;;
*.php) php -f $file ;;
*.mp3 | *.mp4 | *.m4a | *.aac | *.flac) xdg-open $file ;;
*.pdf) xdg-open $file ;;
*.jpg | *.jpeg | *.png | *.gif | *.bmp | *.tiff | *.svg) feh $file ;;
*) xdg-open $file ;;
esac
