#!/usr/bin/env sh
## ? Help : Convert image to png format.
## ? Usage:
## ?    to_png <file>

for f in "$@"; do
	name=$(basename "$f")
	folder=$(dirname "$f")
	name="${name%.*}"
	convert "$f" -background white "$folder/$name.png"
	echo "Imagen convertida: $name -> $name.png"
done
